FROM 117503445/dev-base
LABEL maintainer="117503445"
RUN pacman -Syu dotnet-sdk --noconfirm


# ENV PATH="/root/miniconda3/bin:${PATH}"
# RUN conda init fish
# COPY ./python/.condarc /root/.condarc
# ENV VSC_EXTS="ms-python.black-formatter,formulahendry.code-runner,ms-python.isort,matangover.mypy,ms-python.vscode-pylance,ms-python.python,donjayamanne.python-environment-manager,${VSC_EXTS}"