version: "3.9"
services:
  dev-golang:
    image: 117503445/dev-golang
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    volumes:
      - ./:/root/project
    depends_on:
      - db
    stdin_open: true
    tty: true