version: '3'

tasks:
  default:
    desc: "The default task" 
    cmds:
      - task: run-dev-desktop
      
  build-dev:
    desc: "Build the dev image in China Mainland"
    cmds:
      - docker build -t 117503445/dev -f ./images/dev/Dockerfile --build-arg CHINA_MIRROR=1 .
      - docker run -it --rm -p 44444:4444 117503445/dev

  build-dev-desktop:
    desc: "Build the dev-desktop image in China Mainland"
    cmds:
      - cd scripts/entrypoint && CGO_ENABLED=0 go build -o .
      - docker build -t 117503445/dev-desktop -f ./images/dev-desktop/Dockerfile --build-arg CHINA_MIRROR=1 --progress=plain .

  run-dev-desktop:
    desc: "Run the dev-desktop image"
    deps: ["build-dev-desktop"]
    cmds:
      - docker rm -f dev-desktop || true
      - docker run --rm -p 44444:4444 -p 3000:3000 --name dev-desktop -d 117503445/dev-desktop
  
  run-webtop:
    desc: "Run the webtop image"
    cmds:
      - docker run --rm -p 3000:3000 lscr.io/linuxserver/webtop:arch-kde

  test:
    desc: "Test the dev-desktop container environment"
    deps: ["run-dev-desktop"]
    cmds:
      - cd scripts/go-scripts && go run . test
