version: "3.9"
services:
  dev-kde:
    container_name: dev-kde
    image: 117503445/dev-kde
    restart: unless-stopped
    ports:
      - "6080:6080"
    environment:
      VNC_PASSWD: password
    stdin_open: true
    tty: true