services:
  dev-base:
    image: 117503445/dev-base
    build:
      context: ../
      dockerfile: ./base/Dockerfile
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    volumes:
      - ./:/workspace

    healthcheck:
      test: ["CMD", "test", "!", "-f", "/entrypoint.py.lock"]
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 240s